CREATE SEQUENCE IF NOT EXISTS CLIENT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS CLIENT
(
    ID   BIGINT DEFAULT NEXT VALUE FOR CLIENT_SEQ PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ADDRESS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    STREET    VARCHAR(255),
    CLIENT_ID BIGINT UNIQUE
);

CREATE TABLE IF NOT EXISTS PHONE
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    NUMBER    VARCHAR(50),
    CLIENT_ID BIGINT
);