DROP TABLE IF EXISTS PHONE;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS CLIENT;
DROP SEQUENCE IF EXISTS CLIENT_SEQ;

CREATE SEQUENCE CLIENT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE CLIENT
(
    ID   BIGINT DEFAULT NEXT VALUE FOR CLIENT_SEQ PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE ADDRESS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    STREET    VARCHAR(255),
    CLIENT_ID BIGINT UNIQUE,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID) ON DELETE CASCADE
);

CREATE TABLE PHONE
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    NUMBER    VARCHAR(50),
    CLIENT_ID BIGINT,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID) ON DELETE CASCADE
);